DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS users
(
    user_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email    varchar(20) not null,
    user_login    varchar(20) not null,
    user_name     varchar(50),
    user_birthday date,


    constraint email_format
        CHECK (user_email LIKE '%_@_%._%'),
    constraint login_spaces
        CHECK (user_login NOT LIKE '% %')
);

CREATE TABLE IF NOT EXISTS friends
(
    friends_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    int,
    friend_id  int,
    status     varchar(20) default 'PENDING',

    constraint user_id_fk
        foreign key (user_id)
            references users (user_id),
    constraint friend_id_fk
        foreign key (friend_id)
            references users (user_id)
);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id   integer PRIMARY KEY,
    mpa_name varchar(20)
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id   integer PRIMARY KEY,
    genre_name varchar(20)
);

CREATE TABLE IF NOT EXISTS films
(
    film_id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_description  varchar(200),
    film_name         varchar(50) not null,
    film_release_date date,
    film_duration     int,
    mpa_id            int,
    film_rate         int,

    constraint mpa_fk
        foreign key (mpa_id)
            references mpa (mpa_id),
    constraint positive_duration
        CHECK (film_duration > 0)
);


CREATE TABLE IF NOT EXISTS film_genres
(
    film_genres_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id int,
    genre_id int,
    constraint genre_genres
        foreign key (genre_id)
            references genres (genre_id),
    constraint film_fk
        foreign key (film_id)
            references films (film_id)
);


CREATE TABLE IF NOT EXISTS likes
(
    like_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int,
    film_id int,

    constraint user_fk
        foreign key (user_id)
            references users (user_id),
    constraint film_likes
        foreign key (film_id)
            references films (film_id)
);

